### ISSUE TITLE
Recomended tsv and csv editors to use with firetongue

### ISSUE THREAD

**Issue by Tembac** [larsiusprime/firetongue#16]
Firetongue seems to be very useful but I didn't find an editor that exports Csv or Tsv on the correct format that it needs.

Ms Excel and Drive spreadsheets have the possibility to export csv but the format is no the required by firetongue.

The closer was LibreOffice calc that gives you several options when you are exporting the csv but it is not exactly as required because it is missing the commas at the end lines.

Do you have any advice or list of software that can be used to edit the csv for firetongue?

**Comment by larsiusprime** [comment]
This seems like an oversight on my part -- I'm used to crafting them with Notepad++!

It seems logical that I should be able to support something that is easy to export from Excel and LibreOffice. Let me do some quick investigations and see if I can make the formats a little more flexible.

**Comment by larsiusprime** [comment]
Done. Let me know what you think of the updated readme. 

I've dropped the requirement to put a trailing tab or comma before each endline, though the old format should still work.

We recommend you stick with TSV files, and I've included instructions (with pictures!) for generating firetongue-compliant TSV files from both Microsoft Excel and LibreOffice Calc.

**Comment by Tembac** [comment]
Thanks! This is very helpfull!

I updated the library from github and followed the instructions for LibreOffice but I still had to add tabs at the end lines with notepad++ for it to work fine. Maybe it takes time to update?

**Comment by larsiusprime** [comment]
Perhaps I haven't fully tested it yest. What results did you get? Can you
show me the files you were using?

On Mon, Jan 5, 2015 at 7:15 PM, Tembac <notifications@github.com> wrote:

> Thanks! This is very helpfull!
>
> I updated the library from github and followed the instructions for
> LibreOffice but I still had to add tabs at the end lines with notepad++ for
> it to work fine. Maybe it takes time to update?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/firetongue/issues/16#issuecomment-68811841>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Tembac** [comment]
Sorry. The problem was here. I removed the library and installed again from github. Now it works fine.

Thanks!

**Comment by larsiusprime** [comment]
Great!
