### ISSUE TITLE
Accentuated characters are removed

### ISSUE THREAD

**Issue by ramsestom** [larsiusprime/firetongue#17]
I use csv format encoded in UTF8 and all my accentuated characters (like "é" for example) are removed when I retrieve text with the get() function.
For example, if in my data.csv file I have a ligne:
"$THING","toto tété",
tongue.get("$THING","data") will return "toto tt".
How can I fix this?

**Comment by larsiusprime** [comment]
Is this a data error or a font display error? 

IE, are your accented characters not appearing in the string itself (when using trace() to test, for example), or just not appearing in some text field object you feed the string into? If it's the latter the characters could very well be there but you don't have the right range of characters embedded for the font.

**Comment by ramsestom** [comment]
Oh sorry, my bad. The characters are indeed appearing when displaying the text with trace(). So the issue is not related to firetongue. I feel stupid not having checked this first. Sorry again and thanks for the help.

**Comment by larsiusprime** [comment]
Not a problem! I've done the exact same thing before and it drove me nuts
until I realized what the problem was :)

On Tue, Apr 14, 2015 at 9:34 AM, ramsestom <notifications@github.com> wrote:

> Oh sorry, my bad. The characters are indeed appearing when displaying the
> text with trace(). So the issue is not related to firetongue. I feel stupid
> not having checked this first. Sorry again and thanks for the help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/firetongue/issues/17#issuecomment-92879454>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
