### ISSUE TITLE
#13 bug re-instroduced?

### ISSUE THREAD

**Issue by unixunion** [larsiusprime/firetongue#18]
Hi,

I am getting the same error as in #13. it seems the bug is re-introduced. the neko target is affected. native mac target works. 

Using RPG sample demo. 

```
 keghol  ⓔ  py27  ~  Development  HelloWorld  lime test neko
Invalid field access : __s
Called from firetongue/FireTongue.hx line 1056
Called from firetongue/FireTongue.hx line 1016
Called from firetongue/FireTongue.hx line 180
Called from State_Title.hx line 61
Called from flixel/addons/ui/FlxUI.hx line 111
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 296
Called from flixel/addons/ui/FlxUIRadioGroup.hx line 274
Called from flixel/addons/ui/FlxUICheckBox.hx line 230
Called from flixel/ui/FlxTypedButton.hx line 304
Called from a C function
Called from flixel/addons/ui/FlxUITypedButton.hx line 654
Called from a C function
Called from flixel/addons/ui/FlxUIButton.hx line 210
Called from flixel/ui/FlxTypedButton.hx line 290
Called from openfl/_legacy/events/EventDispatcher.hx line 98
Called from a C function
Called from openfl/_legacy/display/DisplayObject.hx line 258
Called from openfl/_legacy/display/Stage.hx line 924
Called from openfl/_legacy/display/Stage.hx line 401
 keghol  ⓔ  py27  ~  Development  HelloWorld  haxelib list                                                                                     1 
firetongue: [1.0.0]
flixel-addons: [1.1.0]
flixel-demos: [1.1.1]
flixel-templates: [1.0.2]
flixel-tools: [1.0.5]
flixel-ui: [1.0.2]
flixel: [3.3.8]
hxcpp: [3.2.81]
lime-samples: [2.3.0]
lime-tools: [1.5.7]
lime: [2.3.2]
openfl: [3.0.2]
task: [1.0.6]
 keghol  ⓔ  py27  ~  Development  HelloWorld  
```

/K

**Comment by larsiusprime** [comment]
Did you try using the version from github?

**Comment by unixunion** [comment]
I have used the UI example from: https://github.com/HaxeFlixel/flixel-demos/tree/dev/User%20Interface/RPG%20Interface/source

**Comment by larsiusprime** [comment]
Right, I understand, I mean are you using the github version of firetongue, or the latest haxelib release?

Your haxelib says:
```
firetongue: [1.0.0]
```

So this bug may already be fixed in the github code, have you tried it with the github version of firetongue as well?

**Comment by unixunion** [comment]
Ah right, yeah I'm not able to use the github version due to other errors
at the moment relating to the get_locale method.

On Tuesday, April 21, 2015, Lars Doucet <notifications@github.com> wrote:

> Right, I understand, I mean are you using the github version of
> firetongue, or the latest haxelib release?
>
> Your haxelib says:
>
> firetongue: [1.0.0]
>
> So this bug may already be fixed in the github code, have you tried it
> with the github version of firetongue as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/firetongue/issues/18#issuecomment-94806255>
> .
>


--

**Comment by larsiusprime** [comment]
Can you give me an example of the error you're running into using the haxelib version of firetongue? If you do I might be able to release a new version to haxelib to fix this issue.

(please include source code)
