### ISSUE TITLE
Arabic and rigth to left languages

### ISSUE THREAD

**Issue by Tembac** [larsiusprime/firetongue#19]
Hello Lars,

I'm having problems with Arab text. A client sent me the following text to test translating to arabic but he says that the text is showing in the other direction:

ولكنهما لم تيكونا وحدهما في استكشاف الزنازين...

(Github is not allowing me to post arab text on the correct order. It should have the tree dots to the left. Same problem with firetongue)

I don't know if this is something that has to be fixed from the export phase or from firetongue.

**Comment by larsiusprime** [comment]
Are you sure that this is a firetongue issue (which only handles the internal data storage and fetching of text) and not an issue with OpenFL's (or whatever framework you are using) graphical textfield display?

**Comment by Tembac** [comment]
mmm, I'm not sure. Haha.

It is probably a problem of openfl. I'll research.

**Comment by Tembac** [comment]
It was a problem of openfl. The fix is on the forum post.

**Comment by larsiusprime** [comment]
Great thanks for following up!

On Thu, Jun 4, 2015 at 6:33 PM, Tembac <notifications@github.com> wrote:

> It was a problem of openfl. The fix is on the forum post.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/firetongue/issues/19#issuecomment-109092373>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
