### ISSUE TITLE
Crash if files are missing or incomplete

### ISSUE THREAD

**Issue by AndreiRegiani** [larsiusprime/firetongue#6]
Tested both ways:
```
lang.init(Capabilities.language, null, true, true);
lang.init(Capabilities.language, null, false, false);
```

Both ways crash (null reference) if there's no localization folder/files of selected language.

If localization exists but is missing strings, as (true, true) it crashes, but works normally when (false, false), just show the flag string.

**Comment by larsiusprime** [comment]
I'm closing since the temp solution was merged a long time ago, and also I just refactored to clean up the loading functionality so that a user can override it with their own if they must.
